import org.drools.demo.student.Student;

no-loop
rule "Process Student Rule 1"
    ruleflow-group "high"
when
    $student: Student(score >= 100)
then
    System.out.println("Applying  Process Student Rule1 High");
   
    modify($student)
    {
    	setDiscountBonus(20);
    }
    int newScore = $student.getDiscountBonus() + 20; 
    modify($student)
    {
    	
    	setScore(120);
    }
end

rule "Process Student Rule 2"
    ruleflow-group "high"
when
    $student: Student(score == 120)
then
    System.out.println("Applying  Process Student Rule2 High");
    
    modify($student)
    {
    	setDiscountBonus(30);
    }
   
end