import org.drools.demo.student.Student;

no-loop
rule "Process Student Low Rule 1"
    ruleflow-group "low"
when
    $student: Student(score < 50)
then
    System.out.println("Applying  Process Student Rule1 Low");
   
    modify($student)
    {
    	setDiscountBonus(10);
    }
    int newScore = $student.getDiscountBonus() + 5; 
    modify($student)
    {
    	
    	setScore(55);
    }
end

rule "Process Student Low Rule 2"
    ruleflow-group "low"
when
    $student: Student(score == 55)
then
    System.out.println("Applying  Process Student Rule2 Low");
    
    modify($student)
    {
    	setDiscountBonus(20);
    }
   
end